### ISSUE TITLE
extractProcs breaks if previous line is a comment

### ISSUE THREAD

**Issue by thisisnic** [MangoTheCat/sasMap#4]
` "/* step 5.1: sort carrier line file in preparation for transformation */  proc sort data=src.carrier2010line out=carrier2010line;" `

This will not pick up the proc sort, as it treats it as one statement.  Need to add in a call to remove comments before we extract procs.

**Comment by jtalboys** [comment]
```
> test <- "/* step 5.1: sort carrier line file in preparation for transformation */ proc sort data=src.carrier2010line out=carrier2010line;"
> extractProcs(test)
[1] "sort"
```

Looks like this has been resolved at some point (for v1.0 I think) therefore closing this ticket!
