### ISSUE TITLE
Travis build failed since #26

### ISSUE THREAD

**Issue by dmakushin** [MangoTheCat/sasMap#5]
It looks like several of last builds are red. The last successful was three month ago - #26.
Currently the test job cannot pass one of unit tests. 
![image](https://user-images.githubusercontent.com/24922494/32731993-5a1115d6-c89c-11e7-94eb-9f070744bfb8.png)

**Comment by jtalboys** [comment]
Now use gitHub actions to run the CMD check whenever a pr for master is raised. Currently all tests are passing fine so happy to close this ticket.
